version: "3.8"

services:
    php-fpm:
        container_name: php-fpm
        build:
            context: ./../
            dockerfile: ./docker/php-fpm/Dockerfile
            args:
                - PUID=${PUID}
                - PGID=${PGID}
        environment:
            PHP_IDE_CONFIG: "serverName=Docker"
        volumes:
            - ./../:/var/www/
        depends_on:
            - db
    nginx:
        container_name: nginx
        build:
            context: ./nginx
        ports:
            - ${NGINX_HOST_HTTP_PORT}:80
        volumes:
            - ..:/var/www:rw
        depends_on:
            - php-fpm
            - db
    db:
        container_name: db
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
            - ${MYSQL_PORT}:3306
        volumes:
            - ./../mysql:/var/lib/mysql